name: Android CI

on:
  workflow_dispatch:
  push:
    tags:
      - v1.**

jobs:

  build:

    runs-on: ubuntu-18.04


    steps:

      - uses: actions/checkout@v2

      - name: Use Java8
        uses: actions/setup-java@v1
        with:
          java-version: 11
          distribution: 'temurin'
          cache: gradle
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug apk
        run: ./gradlew clean assembleDebug

      - name: Create release and upload apk
        uses: underwindfall/create-release-with-debugapk@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: app.apk
          asset_content_type: application/zip

